export const LANG_COMMON = {
    BACK: 'Quay Lại',
    HOME: 'Trang Chủ',
    VIEW: 'Chi Tiết',
    LOGIN_DECS: 'Xin hãy đăng nhập tài khoản của bạn',
    LOGIN: 'Đăng nhập',
    FORGET_PASS: 'Quên mật khẩu',
    SIGN_UP: 'Đăng kí',
    REMEMBER_ME: 'Nhớ mật khẩu',
    USER_NAME: 'Tên đăng nhập',
    PASS_WORD: 'Mật khẩu',
    LOGOUT: 'Đăng xuất',
    ACCOUNT_SETING: 'Cài đặt tài khoản',
    SETING: 'Cài đặt',
    PROFILE: 'Thông tin'
}
export const LANG_FRUIT = {
    FRUIT_NAME: 'Tên loại quả',
    CREATE_AT: 'Ngày tạo',
    FRUIT_DETAIL : 'Chi Tiết Loại Quả',
    QUANTITY: 'Số lượng',
    ID_FRUIT_CATEGORY: 'Id loại quả',
    RANGE_PRICE: 'Khoảng giá',
    RANGE_PRICE_MAX: 'Giá lớn nhất',
    RANGE_PRICE_MIN: 'Giá nhỏ nhất',
    SHAPE:'Kiểu dáng',
    WEIGHT:'Cân nặng',
    DIMETER: 'Đường kính',
    DIMETER_MAX: 'Đường kính lớn',
    DIMETER_MIN: 'Đường kính nhỏ',
    WEIGHT_MAX: 'Cân nặng lớn',
    WEIGHT_MIN: 'Cân nặng nhỏ',
    PRICE: 'Giá',
    ACTION: 'Hoạt động',
    FRUIT_MANAGEMENT : 'Quản Lý Quả',
    FRUIT_CREATE : 'Tạo các loại quả',
    BTN_CREATE : 'Tạo quả',
    BTN_EDIT: 'Chỉnh sửa quả ',
    SHAPE_1: 'Quả cụp',
    SHAPE_2: 'Quả xòe',
    SHAPE_3: 'Quả cụp to',
    SHAPE_4: 'Quả xòe to',
}
export const LANG_BONSAI = {
    TREE_NAME: 'Tên cây',
    CREATE_AT: 'Ngày tạo',
    DELETE_AT: 'Ngày xóa',
    TREE_DETAIL : 'Chi Tiết Loại Cây',
    QUANTITY: 'Số lượng',
    ID_TREE_CATEGORY: 'Id loại cây',
    RANGE_PRICE: 'Khoảng giá',
    RANGE_PRICE_MAX: 'Giá lớn nhất',
    RANGE_PRICE_MIN: 'Giá nhỏ nhất',
    SHAPE:'Kiểu dáng',
    WEIGHT:'Cân nặng',
    DIMETER: 'Đường kính',
    DIMETER_MAX: 'Đường kính lớn',
    DIMETER_MIN: 'Đường kính nhỏ',
    WEIGHT_MAX: 'Cân nặng lớn',
    WEIGHT_MIN: 'Cân nặng nhỏ',
    PRICE: 'Giá',
    ACTION: 'Hoạt động',
    TREE_MANAGEMENT : 'Quản Lý Cây',
    DESCRIPTION: 'Mô tả về cây'
}
export const LANG_MESS = {
    CONFIRM_DEL_GARDEN : 'Bạn có chắc chắn muốn xóa nhà vườn không ?',
    CONFIRM_DEL_FRUIT : 'Bạn có chắc chắn muốn xóa loại quả không ?',
    CONFIRM_DEL_BLOG : 'Bạn có chắc chắn muốn xóa bài viết không ?',
    
    YES: 'Có',
    NO: 'Không',
    CONFIRM: 'Xác Nhận',
    CANCEL: 'Đóng',
    SUGGEST: 'Bạn có thể nhập khoảng ước lượng',
    REQUIRED: 'là bắt buộc',
    MES_DEL_SUCCESS: 'Xóa nhà vườn thành công !',
    MES_DEL_ERROR: 'Xóa nhà vườn thất bại !',
    MES_CREATE_FRUIT_SUCCESS: 'Tạo loại quả thành công !',
    MES_CREATE_FRUIT_ERR: 'Tạo loại quả thất bại ! (Tên quả có thể đã tồn tại hoặc giá trị khác ko hợp lệ)',
    MES_EDIT_FRUIT_SUCCESS: 'Chỉnh sửa loại quả thành công !',
    MES_EDIT_FRUIT_ERR: 'Chỉnh sửa loại quả thất bại ! (Tên quả có thể đã tồn tại hoặc giá trị khác ko hợp lệ)',
    MES_EDIT_BLOG_SUCCESS: 'Chỉnh sửa bài viết thành công !',
    MES_EDIT_BLOG_ERR: 'Chỉnh sửa bài viết thất bại !',
    MES_DEL_FRUIT_SUCCESS: 'Xóa loại quả thành công !',
    MES_DEL_FRUIT_ERROR: 'Xóa loại quả thất bại !',
    MES_CREATE_BLOG_SUCCESS: 'Tạo bài viết thành công !',
    MES_CREATE_BLOG_ERR: 'Tạo bài viết thất bại !',
    MES_DEL_BLOG_SUCCESS: 'Xóa bài viết thành công !',
    MES_DEL_BLOG_ERROR: 'Xóa bài viết thất bại !',
    MES_CREATE_GARDEN_SUCCESS: 'Tạo nhà vườn thành công !',
    MES_CREATE_GARDEN_ERR: 'Tạo nhà vườn thất bại. Hãy kiểm tra giá trị nhập vào các trường !',
    MES_CFPASS_MATCH: 'Mật khẩu nhập lại phải giống với mật khẩu vừa đặt',
    PHONE_VALIDATE: 'Số điện thoại không hợp lệ'
}
export const LANG_GARDEN = {
    ACTION: 'Hoạt động',
    GARDEN_MANAGEMENT : 'Quản Lý Nhà Vườn',
    GARDEN_DETAIL : 'Chi Tiết Nhà Vườn',
    FUIRT_GARDEN: 'Loại Quả',
    BONSAI_GARDEN: 'Loại Cây',
    USER_NAME: 'Họ Tên',
    FIRST_NAME: 'Họ',
    LAST_NAME: 'Tên',
    DATE: 'Ngày sinh',
    PHONE: 'SĐT',
    EMAIL: 'Email',
    RATE: "Đánh giá",
    BTN_CREATE: 'Tạo Nhà Vườn',
    GARDEN_CREATE : 'Tạo tài khoản nhà vườn',
    PASS_WORD: 'Mật khẩu',
    CF_PASS_WORD: 'Nhập lại mật khẩu',
}

export const LANG_BLOG = {
    ACTION: 'Hoạt động',
    BLOG_MANAGEMENT : 'Quản Lý Bài Viết',
    BLOG_DETAIL : 'Chi Tiết Bài Viết',
    BLOG_CREATE : 'Tạo các bài viết',
    BTN_CREATE : 'Tạo bài viết',
    BTN_EDIT : 'Sửa bài viết',
    BLOG_NAME: 'Tên bài viết',
    DATE: 'Ngày viết',
    TITLE: 'Tiêu đề',
    CONTENT: 'Nội dung bài viết',
    DESCRIPTION: "Mô tả về bài viết"
}